apiVersion: v1
kind: Service
metadata:
  name: pxc-cluster
  labels:
    unit: pxc-cluster
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      name: mysql
    - port: 4444
      name: state-snapshot-transfer
    - port: 4567
      name: replication-traffic
    - port: 4568
      name: incremental-state-transfer
  selector:
    unit: pxc-cluster
