apiVersion: v1
kind: Service
metadata:
  name: pxc-node1
  labels:
    node: pxc-node1
spec:
  ports:
    - port: 3306
      name: mysql
    - port: 4444
      name: state-snapshot-transfer
    - port: 4567
      name: replication-traffic
    - port: 4568
      name: incremental-state-transfer
  selector:
    node: pxc-node1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pxc-node1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        node: pxc-node1
        unit: pxc-cluster
    spec:
      containers:
        - resources:
            limits:
              cpu: 0.3
          image: lushdigital/mysql-galera
          name: pxc-node1
          ports:
            - containerPort: 3306
            - containerPort: 4444
            - containerPort: 4567
            - containerPort: 4568
          env:
            - name: GALERA_CLUSTER
              value: "true"
            - name: WSREP_CLUSTER_ADDRESS
              value: gcomm://
            - name: WSREP_SST_USER
              value: WSREP_SST_USER_VAR
            - name: WSREP_SST_PASSWORD
              value: WSREP_SST_PASSWORD_VAR
            - name: MYSQL_USER
              value: MYSQL_USER_VAR
            - name: MYSQL_PASSWORD
              value: MYSQL_PASSWORD_VAR
            - name: MYSQL_ROOT_PASSWORD
              value: MYSQL_ROOT_PASSWORD_VAR
