apiVersion: v1
kind: Service
metadata:
  name: drupal
  namespace: default
  labels:
    k8s-app: drupal
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "drupal"
spec:
  selector:
    k8s-app: drupal
  ports:
  - name: http
    port: 80
    protocol: TCP
  externalIPs:
  - $EXT_IP1


---

apiVersion: v1
kind: ReplicationController
metadata:
  name: drupal
  namespace: default
  labels:
    k8s-app: drupal
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: drupal
    version: v1
  template:
    metadata:
      labels:
        k8s-app: drupal
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: drupal
        image: drupal:7
        resources:
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 5
